name: $(Date:yyyyMMdd).$(Rev:r)
variables:
  - name: BuildConfiguration
    value: Release
  - name: BuildNumber
    value: $[counter('versioncounter', 11128)]
  - name: Codeql.Enabled
    value: true
  - name: IsTargetMultiFramework
    value: true
  - name: LocalFeed
    value: $(UserProfile)\localfeed
  - name: MSBuildProperties
    value: Configuration=$(BuildConfiguration);BuildNumber=$(BuildNumber);VersionSuffix=$(VersionSuffix);IsTargetMultiFramework=$(IsTargetMultiFramework);SignType=$(SignType);IsFinalBuild=${{parameters.isFinalBuild}}
  - name: SignType
    value: real
  - name: TeamName
    value: Azure SignalR Team
  - name: VersionSuffix
    value: preview1-$(BuildNumber)
parameters:
  - name: isFinalBuild
    type: boolean
    default: false
  - name: releaseEmulator
    type: boolean
    default: false
  - name: releaseSDKCore
    type: boolean
    default: false
  - name: releaseServerlessProtocol
    type: boolean
    default: false
resources:
  repositories:
    - repository: self
      type: git
      ref: refs/heads/dev
    - repository: 1esPipelines
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
trigger:
  branches:
    include:
      - dev
  paths:
    include:
      - src
  batch: true
pr: none
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      os: windows
      name: MSEngSS-MicroBuild2022-1ES
    customBuildTags:
      - MigrationTooling-mseng-VSJava-8484-Tool
    sdl:
      eslint:
        enabled: false
    stages:
      - stage: Stage
        jobs:
          - job: SDK_Partner_Release
            displayName: SDK Partner Release
            steps:
              - task: PowerShell@2
                displayName: Create Dummy File
                inputs:
                  targetType: 'inline'
                  script: |
                    $artifactPath = "$(Pipeline.Workspace)/Artifact"
                    if (-not (Test-Path -Path $artifactPath)) {
                      New-Item -Path $artifactPath -ItemType Directory
                    }
                    $dummyFilePath = Join-Path $artifactPath "dummy.txt"
                    "This is a test file for AzCopy." | Out-File -FilePath $dummyFilePath
              
              - task: PowerShell@2
                displayName: Uninstall AzureRM Module
                inputs:
                  targetType: 'inline'
                  script: |
                    Get-Module -ListAvailable -Name AzureRM* | Uninstall-Module -Force
              - task: AzureFileCopy@6
                displayName: SDK Partner Release AzCopy
                inputs:
                  SourcePath: $(Pipeline.Workspace)/Artifact/*
                  azureSubscription: azuresdkpartnerdrops_javatooling
                  Destination: AzureBlob
                  storage: azuresdkpartnerdrops
                  ContainerName: drops
                  BlobPrefix: azure-signalr/dotnet/$(BuildNumber)
