version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - dev
  - master
build_script:
- cmd: ./build.cmd -ci /p:BuildNumber=%APPVEYOR_BUILD_NUMBER%
test: off
