name: Gated-OSX
on:
 push:
   branches:
    - 'releases/**'
    - dev
 pull_request:
   branches:
    - 'releases/**'
    - dev
jobs:
  build_osx:
    runs-on: macOS-latest
    strategy:
      fail-fast: false # Disable the auto cancelling of all in-progress and queued jobs in the matrix if any job in the matrix fails.
      matrix:
        dotnet-version: [ '9.0.x', '8.0.x' ]
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
    - uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
      id: filter
      with:
        filters: |
          src:
          - 'src/**'
          - 'test/**'
          - 'build/**'
          - 'samples/**'
          - '*.cmd'
          - '*.ps1'
          - '**.props'
          - '**.csproj'
          - '**.targets'
          - '*.sh'
          - '*.sln'
    - name: Update SubModules
      if: steps.filter.outputs.src == 'true'
      run: git submodule update --init --recursive
    - name: Setup dotnet ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    #  Remove it when .NET 11 is GA.
    - name: Setup .NET 11 daily SDK
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
      with:
        dotnet-version: '11.0.x'
        dotnet-quality: 'daily'
    - name: Display dotnet version
      run: dotnet --version
    - name: Build with dotnet
      run: |
        dotnet build AzureSignalR.sln /p:DisableNet461Tests=true
      if: steps.filter.outputs.src == 'true'
    - name: Test
      run: dotnet test --no-build --logger trx --results-directory "TestResults-ubuntu-${{ matrix.dotnet-version }}"
    - name: Upload dotnet test results
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: dotnet-results-${{ matrix.dotnet-version }}
        path: TestResults-ubuntu-${{ matrix.dotnet-version }}
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
