name: Gated-Ubuntu
on: 
 push:
   branches: 
    - master
    - dev
 pull_request:
   branches: 
    - master
    - dev
jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v2.2.0
      id: filter
      with:
        filters: |
          src:
          - 'src/**'
          - 'test/**'
          - 'build/**'
          - 'samples/**'
          - '*.cmd'
          - '*.ps1'
          - '**.props'
          - '**.csproj'
          - '**.targets'
          - '*.sh'
          - '*.sln'
    - name: Update SubModules
      run: git submodule update --init --recursive
      if: steps.filter.outputs.src == 'true'
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          7.0.x
          6.0.x

    - name: Set Dotnet Version
      run: echo "DOTNET_VERSION=${{ steps.dotnet-setup.outputs.dotnet-version }}" >> $GITHUB_ENV

    - name: Build with dotnet
      run:  "dotnet build AzureSignalR.sln /p:DisableNet461Tests=true"
      if: steps.filter.outputs.src == 'true'
    - name: Test
      run: dotnet test --no-build --logger trx --results-directory "TestResults-ubuntu-$DOTNET_VERSION"
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-results-$DOTNET_VERSION
        path: TestResults-ubuntu-$DOTNET_VERSION
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
