name: Gated-Ubuntu
on: 
 push:
   paths:
    - 'src/**'
    - 'test/**'
    - '*.cmd'
    - '*.ps1'
    - '*.props'
    - '*.targets'
    - '*.sh'
    - '*.sln'
   branches: 
    - master
    - dev
 pull_request:
   paths:
    - 'src/**'
    - 'test/**'
    - '*.cmd'
    - '*.ps1'
    - '*.props'
    - '*.targets'
    - '*.sh'
    - '*.sln'
   branches: 
    - master
    - dev
jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Update SubModules
      run: git submodule update --init --recursive
    
    - name: Build with dotnet
      run:  "./build.sh --ci /p:DisableNet461Tests=true"
