name: Gated-Ubuntu
on: 
 push:
   branches: 
     - master
     - dev
 pull_request:
   branches: 
     - master
     - dev
jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Update SubModules
      run: git submodule update --init --recursive
    
    - name: Build with dotnet
      run:  "./build.sh --ci /p:DisableNet461Tests=true"
